<?php
/**
 * Created by PhpStorm.
 * User: ps
 * Date: 19/10/18
 * Time: 01:12 PM
 */

namespace Punksolid\Wialon\Tests;

use Orchestra\Testbench\TestCase;
use Punksolid\Wialon\Geofence;


class GeofenceTest extends TestCase
{


    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('services.wialon.token', '5dce19710a5e26ab8b7b8986cb3c49e58C291791B7F0A7AEB8AFBFCEED7DC03BC48FF5F8');
    }
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    public function test_find_geofence_by_name()
    {

        $geofence = Geofence::findByName("my_geofence");

        $this->assertEquals("my_geofence", $geofence->n);
    }
}