<?php

namespace Punksolid\Wialon\Tests;

use Faker\Factory;
use Orchestra\Testbench\TestCase;
use Punksolid\Wialon\Wialon;

/**
 *  Corresponding Class to test YourClass class
 *
 *  For each class in your library, there should be a corresponding Unit-Test for it
 *  Unit-Tests should be as much as possible independent from other test going on.
 *
 * @author yourname
 */
class WialonTest extends TestCase
{

    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
//        $app['services']->set('database.default', 'testbench');

        $app['config']->set('services.wialon.token', '5dce19710a5e26ab8b7b8986cb3c49e58C291791B7F0A7AEB8AFBFCEED7DC03BC48FF5F8');
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    /**
     * Just check if the YourClass has no syntax error
     *
     * This is just a simple check to make sure your library has no syntax error. This helps you troubleshoot
     * any typo before you even use this library in a real project.
     *
     */
    public function test_simple_connection_make_login()
    {
        $wialon_token = getenv('WIALON_SECRET');

        $wialon_api = new \Punksolid\Wialon\Wialon();
        $result = $wialon_api->login($wialon_token);
        $json = json_decode($result, true);

//        print_r($json);
//
//        if (!isset($json['error'])) {
//            echo $wialon_api->core_search_item('{"id":717359,"flags":0x1}');
//            $wialon_api->logout();
//        } else {
//            echo \Punksolid\Wialon\WialonError::error($json['error']);
//        }

        $this->assertArrayHasKey("eid", $json);
        $this->assertArraySubset(["th" => getenv('WIALON_SECRET')], $json, "Makes login and retrieves eid");

    }


    function getData2()
    {
        $wialon_conn = new Wialon();
        $arregloItemByProp = array('spec' => array('itemsType' => 'avl_unit',
            'propName' => 'sys_name',
            'propValueMask' => '*',
            'sortType' => 'sys_name',
            'propType' => 'property'
        ),
            'force' => 1,
            'flags' => 5129,
            'from' => 0,
            'to' => 0);
        $arregloProperties = $wialon_conn->core_search_items(json_encode($arregloItemByProp) . "&sid=" . $this->sid);
        //echo 'ARRAY: '.$arregloProperties.'<br>';
        $dataReturn = json_decode($arregloProperties, true);
        return $dataReturn;
    }

    public function test_list_units_original()
    {
        $wialon_api = new \Punksolid\Wialon\Wialon();

        $units = $wialon_api->listUnits();
        dd($units->first);
        $this->assertObjectHasAttribute("id",$units->first(), "Unit has id");
        $this->assertObjectHasAttribute("mu",$units->first(), "Unit has measure units");
        $this->assertObjectHasAttribute("nm",$units->first(),"Unit has name");
        $this->assertObjectHasAttribute("cls",$units->first(), "Unit has  superclass ID: avl_unit");
        $this->assertObjectHasAttribute("uacl",$units->first(), "Unit has uacl current user access level for unit");



    }

    public function test_get_user_name()
    {
        $wialon_api = new \Punksolid\Wialon\Wialon();
        $result = $wialon_api->login("5dce19710a5e26ab8b7b8986cb3c49e58C291791B7F0A7AEB8AFBFCEED7DC03BC48FF5F8");
        $result = json_decode($result);
        $mi_user = new \Punksolid\Wialon\User($result->user);

        $this->assertEquals("SdkDemo", $mi_user->nm);

    }

    public function test_list_notifications()
    {
        $wialon_api = new Wialon();
        $notifications = $wialon_api->listNotifications();

        dd($notifications->first());
    }

    public function test_create_geofence()
    {
        $faker = Factory::create();

        $wialon_api = new Wialon();
        $resource = $wialon_api->createResource($faker->word.$faker->unique()->word);
        $lat = $faker->latitude;
        $lon = $faker->longitude;
        $geofence = $wialon_api->createGeofence(
            $resource->id,
            $faker->word.$faker->unique()->word,
            $lat,
            $lon,
            $faker->numberBetween(800,1100),
            3
        );

        $this->assertObjectHasAttribute("n",$geofence,"Geofence has name");
        $this->assertObjectHasAttribute("d",$geofence, "Geofence has description");
        $this->assertObjectHasAttribute("id",$geofence, "Geofence has id");
        $this->assertObjectHasAttribute("f",$geofence, "Geofence has flags");
        $this->assertObjectHasAttribute("t",$geofence, "Geofence has type specification");
        $this->assertObjectHasAttribute("e",$geofence, "Geofence has checksum");
        $this->assertObjectHasAttribute("b",$geofence, "Geofence has configuration attributes");

    }

    public function test_create_resource()
    {
        $wialon_api = new  \Punksolid\Wialon\Wialon();
        $resource = $wialon_api->createResource("punksolid@twitter.com");

        dd($resource);
    }

    public function test_tracking_unit()
    {
        $wialon_api = new  \Punksolid\Wialon\Wialon();
        $seconds = 30;
        for ($seconds; $seconds >= 1; $seconds--) {
            sleep(1);
            dump($wialon_api->checkEvents());
        }

    }


}
