<?php

namespace Punksolid\Wialon\Tests;

use Faker\Factory;
use Orchestra\Testbench\TestCase;
use Punksolid\Wialon\Geofence;
use Punksolid\Wialon\Notification;
use Punksolid\Wialon\Resource;
use Punksolid\Wialon\Unit;
use Punksolid\Wialon\Wialon;

/**
 *  Corresponding Class to test YourClass class
 *
 *  For each class in your library, there should be a corresponding Unit-Test for it
 *  Unit-Tests should be as much as possible independent from other test going on.
 *
 * @author yourname
 */
class WialonTest extends TestCase
{

    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
//        $app['services']->set('database.default', 'testbench');

        $app['config']->set('services.wialon.token', '5dce19710a5e26ab8b7b8986cb3c49e58C291791B7F0A7AEB8AFBFCEED7DC03BC48FF5F8');
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    /**
     * Just check if the YourClass has no syntax error
     *
     * This is just a simple check to make sure your library has no syntax error. This helps you troubleshoot
     * any typo before you even use this library in a real project.
     *
     */
    public function test_simple_connection_make_login()
    {
        $wialon_token = getenv('WIALON_SECRET');

        $wialon_api = new \Punksolid\Wialon\Wialon();
        $result = $wialon_api->login($wialon_token);
        $json = json_decode($result, true);

//        print_r($json);
//
//        if (!isset($json['error'])) {
//            echo $wialon_api->core_search_item('{"id":717359,"flags":0x1}');
//            $wialon_api->logout();
//        } else {
//            echo \Punksolid\Wialon\WialonError::error($json['error']);
//        }

        $this->assertArrayHasKey("eid", $json);
        $this->assertArraySubset(["th" => getenv('WIALON_SECRET')], $json, "Makes login and retrieves eid");

    }


    function getData2()
    {
        $wialon_conn = new Wialon();
        $arregloItemByProp = array('spec' => array('itemsType' => 'avl_unit',
            'propName' => 'sys_name',
            'propValueMask' => '*',
            'sortType' => 'sys_name',
            'propType' => 'property'
        ),
            'force' => 1,
            'flags' => 5129,
            'from' => 0,
            'to' => 0);
        $arregloProperties = $wialon_conn->core_search_items(json_encode($arregloItemByProp) . "&sid=" . $this->sid);
        //echo 'ARRAY: '.$arregloProperties.'<br>';
        $dataReturn = json_decode($arregloProperties, true);
        return $dataReturn;
    }

    public function test_list_units_original()
    {
        $wialon_api = new \Punksolid\Wialon\Wialon();

        $units = $wialon_api->listUnits();

        $this->assertObjectHasAttribute("id", $units->first(), "Unit has id");
        $this->assertObjectHasAttribute("mu", $units->first(), "Unit has measure units");
        $this->assertObjectHasAttribute("nm", $units->first(), "Unit has name");
        $this->assertObjectHasAttribute("cls", $units->first(), "Unit has  superclass ID: avl_unit");
        $this->assertObjectHasAttribute("uacl", $units->first(), "Unit has uacl current user access level for unit");


    }

    public function test_get_user_name()
    {
        $wialon_api = new \Punksolid\Wialon\Wialon();
        $result = $wialon_api->login("5dce19710a5e26ab8b7b8986cb3c49e58C291791B7F0A7AEB8AFBFCEED7DC03BC48FF5F8");
        $result = json_decode($result);
        $mi_user = new \Punksolid\Wialon\User($result->user);

        $this->assertEquals("SdkDemo", $mi_user->nm);

    }

    public function test_list_notifications()
    {
        $wialon_api = new Wialon();
        $notifications = $wialon_api->listNotifications();

        dd($notifications->first());
    }

    public function test_create_geofence()
    {
        $faker = Factory::create();

        $wialon_api = new Wialon();
        $resource = $wialon_api->createResource($faker->word . $faker->unique()->word);
        $lat = $faker->latitude;
        $lon = $faker->longitude;

        $geofence = Geofence::make(
            $resource->id,
            $faker->word . $faker->unique()->word,
            $lat,
            $lon,
            $faker->numberBetween(800, 1100),
            3);

        $this->assertObjectHasAttribute("n", $geofence, "Geofence has name");
        $this->assertObjectHasAttribute("d", $geofence, "Geofence has description");
        $this->assertObjectHasAttribute("id", $geofence, "Geofence has id");
        $this->assertObjectHasAttribute("f", $geofence, "Geofence has flags");
        $this->assertObjectHasAttribute("t", $geofence, "Geofence has type specification");
        $this->assertObjectHasAttribute("e", $geofence, "Geofence has checksum");
        $this->assertObjectHasAttribute("b", $geofence, "Geofence has configuration attributes");

    }

    public function test_find_geofence_by_id()
    {
        $faker = Factory::create();

        $wialon_api = new Wialon();
        $resource = $wialon_api->createResource($faker->word . $faker->unique()->word);
        $lat = $faker->latitude;
        $lon = $faker->longitude;

        $geofence = Geofence::make(
            $resource->id,
            $faker->word . $faker->unique()->word,
            $lat,
            $lon,
            $faker->numberBetween(800, 1100),
            3);

        $new_geofence = Geofence::find($geofence->id);
        $this->assertEquals($geofence->n, $new_geofence->n);
    }

    public function test_create_resource()
    {
        /**
         *
         * Punksolid\Wialon\Resource {#233
         * +nm: "punksolid_test3"
         * +cls: 3
         * +id: 18158941
         * +mu: 0
         * +uacl: 60606282529791
         * }
         *
         */
        $wialon_api = new  \Punksolid\Wialon\Wialon();
        $resource = $wialon_api->createResource("punksolid_test3");
        dump($resource);
        $this->assertObjectHasAttribute("nm", $resource);
    }

    public function test_tracking_unit()
    {
        $wialon_api = new  \Punksolid\Wialon\Wialon();
        $seconds = 30;
        for ($seconds; $seconds >= 1; $seconds--) {
            sleep(1);
            dump($wialon_api->checkEvents());
        }

    }

    public function test_create_unit()
    {
        $api_wialon = new Wialon();

        $unit = $api_wialon->createUnit(
            "BicicletaChema"
        );

        $this->assertObjectHasAttribute("id", $unit, "Unit has id");
        $this->assertObjectHasAttribute("mu", $unit, "Unit has measure units");
        $this->assertObjectHasAttribute("nm", $unit, "Unit has name");
        $this->assertObjectHasAttribute("cls", $unit, "Unit has  superclass ID: avl_unit");
        $this->assertObjectHasAttribute("uacl", $unit, "Unit has uacl current user access level for unit");

    }

    public function test_find_unit_by_id()
    {

        $unit = Unit::find(18158671);

        $this->assertEquals("BicicletaPunksolid15", $unit->getName());
        $this->assertObjectHasAttribute("id", $unit, "Unit has id");
        $this->assertObjectHasAttribute("mu", $unit, "Unit has measure units");
        $this->assertObjectHasAttribute("nm", $unit, "Unit has name");
        $this->assertObjectHasAttribute("cls", $unit, "Unit has  superclass ID: avl_unit");
        $this->assertObjectHasAttribute("uacl", $unit, "Unit has uacl current user access level for unit");

    }

    public function test_destroy_unit()
    {
        $api_wialon = new Wialon();

        $unit = $api_wialon->createUnit(
            "Patines2"
        );

        $this->assertEquals(true, $api_wialon->destroyUnit($unit));
    }

    public function test_create_notification()
    {
        $faker = new Factory();
        $units = (new Wialon())->listUnits()->take(2);
        $resource = Resource::findByName('punksolid_test');
        $wialon_api = new Wialon();
        $resource = $wialon_api->createResource($faker->word . $faker->unique()->word);
        $lat = $faker->latitude;
        $lon = $faker->longitude;

        $geofence = $wialon_api->createGeofence(
            $resource->id,
            $faker->word . $faker->unique()->word,
            $lat,
            $lon,
            $faker->numberBetween(800, 1100),
            3
        );

        $notification = Notification::make(
            $resource,
            $geofence,
            $units,
            true,
            "SeEstanRobandomiBici"
        );


        dd($notification);
    }

    public function test_find_resource_by_name()
    {
        $resource = Resource::findByName('punksolid_test');

        $this->assertEquals("punksolid_test", $resource->nm);
        $this->assertObjectHasAttribute("id",$resource);
    }
}
